- name: Pull registry.fedoraproject.org/f33/fedora-toolbox
  command: podman pull registry.fedoraproject.org/f33/fedora-toolbox
  register: _podman
  until: _podman.rc == 0
  retries: 5
  delay: 10

- name: Pull registry.fedoraproject.org/f29/fedora-toolbox
  command: podman pull registry.fedoraproject.org/f29/fedora-toolbox
  register: _podman
  until: _podman.rc == 0
  retries: 5
  delay: 10
